image: node:latest

stages:
  - build
  - test
  - publish

.cache: &cache
  key: build-cache
  paths:
    - node_modules/
    - .npmrc
  policy: pull

build:
  stage: build
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  script:
    - npm install
  cache:
    <<: *cache
    policy: push

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - npm run test:ci
  cache:
    <<: *cache
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

publish:
  stage: publish
  cache:
    <<: *cache
    policy: pull
  only:
    - tags
  dependencies:
    - build
  script:
    - npm publish --access public
