image: node:latest
stages:
  - deploy

deploy:
  stage: deploy
#  only:
#    - tags
  script:
#    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
  environment: production
